"""updating a column.

Revision ID: 64aa06c1fd54
Revises: 65dca5427412
Create Date: 2022-07-21 21:50:46.245125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64aa06c1fd54'
down_revision = '65dca5427412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artists', 'venue_hunt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('venue_hunt', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
