"""Worked on my models

Revision ID: 86639d781059
Revises: fb9f348923ca
Create Date: 2022-07-26 11:26:50.990730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86639d781059'
down_revision = 'fb9f348923ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=False))
    op.drop_column('venues', 'ggenres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('ggenres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
