"""Fixed a bug

Revision ID: d0f44a1d25ac
Revises: 89cbd5500e06
Create Date: 2022-07-25 14:00:45.728082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f44a1d25ac'
down_revision = '89cbd5500e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
