"""Worked on my models

Revision ID: fb9f348923ca
Revises: abcedef07361
Create Date: 2022-07-26 09:38:46.525839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9f348923ca'
down_revision = 'abcedef07361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('upcoming', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('ggenres', sa.String(length=120), nullable=False))
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.alter_column('venues', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('venues', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('venues', 'past_shows_count')
    op.drop_column('venues', 'upcoming_shows_count')
    op.drop_column('venues', 'ggenres')
    op.drop_column('shows', 'upcoming')
    op.drop_column('artists', 'past_shows_count')
    op.drop_column('artists', 'upcoming_shows_count')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
